-- Run this in Supabase SQL Editor

create table if not exists ride_messages (
  id          bigint generated by default as identity primary key,
  ride_id     int not null references rides(id) on delete cascade,
  sender_id   uuid not null references profiles(id) on delete cascade,
  body        text not null,
  created_at  timestamptz default now()
);

create index if not exists ride_messages_ride_id_idx on ride_messages(ride_id);
alter table ride_messages enable row level security;

drop policy if exists "Ride thread read" on ride_messages;
drop policy if exists "Ride thread write" on ride_messages;

create policy "Ride thread read" on ride_messages for select using (
  exists (select 1 from rides r where r.id = ride_messages.ride_id and r.driver_id = auth.uid())
  or exists (select 1 from ride_participants rp where rp.ride_id = ride_messages.ride_id and rp.user_id = auth.uid())
  or (
    auth.uid() is not null
    and exists (select 1 from rides r where r.id = ride_messages.ride_id and r.status = 'scheduled')
  )
);

create policy "Ride thread write" on ride_messages for insert with check (
  sender_id = auth.uid()
  and (
    exists (select 1 from rides r where r.id = ride_messages.ride_id and r.driver_id = auth.uid())
    or exists (select 1 from ride_participants rp where rp.ride_id = ride_messages.ride_id and rp.user_id = auth.uid())
    or exists (
      select 1 from rides r
      where r.id = ride_messages.ride_id
        and r.status = 'scheduled'
        and r.driver_id is distinct from auth.uid()
    )
  )
);

alter table ride_messages replica identity full;
alter publication supabase_realtime add table ride_messages;
