-- Pipeline 1: Data Enrichment for AI Matching Engine
-- Run in Supabase SQL Editor

-- Add coordinate columns to rides (driver departure point)
ALTER TABLE rides
  ADD COLUMN IF NOT EXISTS departure_lat  double precision,
  ADD COLUMN IF NOT EXISTS departure_lng  double precision;

-- Add coordinate columns to ride_requests (rider pickup point)
ALTER TABLE ride_requests
  ADD COLUMN IF NOT EXISTS pickup_lat  double precision,
  ADD COLUMN IF NOT EXISTS pickup_lng  double precision;

-- Persist computed match suggestions
CREATE TABLE IF NOT EXISTS ride_matches (
  id           bigint generated by default as identity primary key,
  ride_id      int not null references rides(id) on delete cascade,
  request_id   int not null references ride_requests(id) on delete cascade,
  score        double precision not null,
  status       text not null default 'pending' check (status in ('pending', 'accepted', 'dismissed')),
  created_at   timestamptz default now(),
  unique (ride_id, request_id)
);

ALTER TABLE ride_matches enable row level security;

-- Anyone involved in the ride or request can read their matches
CREATE POLICY "Ride match read" ON ride_matches FOR SELECT USING (
  EXISTS (SELECT 1 FROM rides r WHERE r.id = ride_matches.ride_id AND r.driver_id = auth.uid())
  OR EXISTS (SELECT 1 FROM ride_requests rr WHERE rr.id = ride_matches.request_id AND rr.requester_id = auth.uid())
);

-- Driver can insert matches (triggered client-side when they post a ride)
CREATE POLICY "Ride match insert" ON ride_matches FOR INSERT WITH CHECK (
  EXISTS (SELECT 1 FROM rides r WHERE r.id = ride_matches.ride_id AND r.driver_id = auth.uid())
);

-- Both parties can update status (accept/dismiss)
CREATE POLICY "Ride match update" ON ride_matches FOR UPDATE USING (
  EXISTS (SELECT 1 FROM rides r WHERE r.id = ride_matches.ride_id AND r.driver_id = auth.uid())
  OR EXISTS (SELECT 1 FROM ride_requests rr WHERE rr.id = ride_matches.request_id AND rr.requester_id = auth.uid())
);
