-- Run this in Supabase SQL Editor

create table if not exists ride_ratings (
  id          bigint generated by default as identity primary key,
  ride_id     int not null references rides(id) on delete cascade,
  rater_id    uuid not null references profiles(id) on delete cascade,
  rated_id    uuid not null references profiles(id) on delete cascade,
  stars       smallint not null check (stars between 1 and 5),
  comment     text,
  created_at  timestamptz default now(),
  unique (ride_id, rater_id)
);

alter table ride_ratings enable row level security;

-- Anyone can insert their own rating
create policy "insert own rating" on ride_ratings
  for insert with check (auth.uid() = rater_id);

-- Public read
create policy "read ratings" on ride_ratings
  for select using (true);
